apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hellosample2
spec:
  selector:
    matchLabels:
      app: hellosample2
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: hellosample2
    spec:
      containers:
      - name: testla
        image: myanees/aneesm
        imagePullPolicy: "Always"
        ports:
        - containerPort: 2123
      imagePullSecrets:
        - name: regcred
