apiVersion: v1
kind: Pod
metadata:
  name: hellosample1
  labels:
    app: hellosample1
spec:
  containers:
  - name: testla
    image: myanees/testla
    ports:
    - name: nodejs-port
      containerPort: 2123
